apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000